baseURL: http://www.example.com
title: homepage
theme: hugo-coder
languageCode: en
defaultContentLanguage: en

paginate: 20

#enableEmoji: yes

markup:
  highlight:
    style: native
params:
  author: Zhang Han
  avatarURL: images/head.jpg
  colorScheme: auto
  #commit: https://github.com/luizdepra/hugo-coder/tree/
  #customCSS: []
  #customJS: []
  #customRemoteJS: []
  #customSCSS: []
  dateFormat: January 2, 2006
  description: Zhang Han's personal website
  hideColorSchemeToggle: no
  info:
    - math USTC
    - undergraduate
  keywords: blog,personal
  maxSeeAlsoItems: 5
  rtl: no
  since: 2023
  social:
    - icon: fa fa-2x fa-github
      name: Github
      url: https://github.com/invierno0204
      weight: 1
   
taxonomies:
  author: authors
  category: categories
  series: series
  tag: tags
  

menu:
    main:
      - name: About
        url: about/
        weight: 1
      - name: Blog
        url: posts/
        weight: 2
      - name: Projects
        url: projects/
        weight: 3
      - name: Contact me
        url: contact/
        weight: 4
 